// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApLhW8fkVyaM4Sch6WmnKVgQW8AJ5Qy1U',
    appId: '1:1001371831855:web:a3c73eab9aeb1e3a6a00da',
    messagingSenderId: '1001371831855',
    projectId: 'lapak-bantul-c9a9c',
    authDomain: 'lapak-bantul-c9a9c.firebaseapp.com',
    storageBucket: 'lapak-bantul-c9a9c.firebasestorage.app',
    measurementId: 'G-M3S1BXTJ2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-yx-clt_RnivAmO9l0MTHeA2DII0F8fQ',
    appId: '1:1001371831855:android:bdd84c52100f15a46a00da',
    messagingSenderId: '1001371831855',
    projectId: 'lapak-bantul-c9a9c',
    storageBucket: 'lapak-bantul-c9a9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5ijAVNZFAPxddeKNIw5EoVgU2G2K9Jns',
    appId: '1:1001371831855:ios:aabd943d033b81446a00da',
    messagingSenderId: '1001371831855',
    projectId: 'lapak-bantul-c9a9c',
    storageBucket: 'lapak-bantul-c9a9c.firebasestorage.app',
    iosBundleId: 'com.example.percobaan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5ijAVNZFAPxddeKNIw5EoVgU2G2K9Jns',
    appId: '1:1001371831855:ios:aabd943d033b81446a00da',
    messagingSenderId: '1001371831855',
    projectId: 'lapak-bantul-c9a9c',
    storageBucket: 'lapak-bantul-c9a9c.firebasestorage.app',
    iosBundleId: 'com.example.percobaan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApLhW8fkVyaM4Sch6WmnKVgQW8AJ5Qy1U',
    appId: '1:1001371831855:web:229d245398396eae6a00da',
    messagingSenderId: '1001371831855',
    projectId: 'lapak-bantul-c9a9c',
    authDomain: 'lapak-bantul-c9a9c.firebaseapp.com',
    storageBucket: 'lapak-bantul-c9a9c.firebasestorage.app',
    measurementId: 'G-3Z4G2FCCY9',
  );
}
